<?php
// Start the session
session_start();

// Include database connection
include('config.php');

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: login.php');
    exit;
}

// Fetch user role
$role = isset($_SESSION['role']) ? $_SESSION['role'] : '';

// Only allow access for super admin
if ($role !== 'super_admin') {
    header('Location: dashboard.php');
    exit;
}

// Include TCPDF library
require_once('tcpdf.php'); // Ensure the path is correct

// Fetch mentee and mentor activity data
$sql = "SELECT 
            p.journal_name, p.category, p.index_type, p.collaboration, p. author_type, p.file_path, p.submission_date, p.paper_status,
            IF(p.validation_status IS NULL, 'Not validated', p.validation_status) AS validation_status, 
            p.correction, p.comment, 
            IF(p.validation_status = 'Validated', p.validation_datetime, '') AS validation_datetime,
            u1.fullname AS mentee_name, u2.fullname AS mentor_name,
            pl.link AS publication_link
        FROM publications p
        LEFT JOIN users u1 ON p.user_id = u1.user_id
        LEFT JOIN mentor_mentee mm ON p.user_id = mm.mentee_id
        LEFT JOIN users u2 ON mm.mentor_id = u2.user_id
        LEFT JOIN publication_links pl ON p.publication_id = pl.publication_id
        ORDER BY p.validation_datetime DESC, p.journal_name ASC";

$stmt = $conn->prepare($sql);
$stmt->execute();
$result = $stmt->get_result();

// Create new PDF document
$pdf = new TCPDF('L', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);


// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Activity Report');
$pdf->SetSubject('Activity Report');
$pdf->SetKeywords('TCPDF, PDF, report, activity');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Publication Mentorship Marvel Report', 'Generated by Mentor-Mentee e-Buddy System');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Table header
$tbl = '<table cellspacing="0" cellpadding="1" border="1">
    <tr>
        <th>Mentor Name</th>
        <th>Mentee Name</th>
        <th>Journal Name</th>
        <th>Category</th>
        <th>Index Type</th>
        <th>Collaboration</th>
        <th>Author</th>
        <th>File Path</th>
        <th>Submission Date</th>
        <th>Status</th>
        <th>Validation Date & Time</th>
        <th>Paper Status</th>
        <th>Link</th>
    </tr>';

// Table body
while ($row = $result->fetch_assoc()) {
    $tbl .= '<tr>
        <td>' . htmlspecialchars($row['mentor_name']) . '</td>
        <td>' . htmlspecialchars($row['mentee_name']) . '</td>
        <td>' . htmlspecialchars($row['journal_name']) . '</td>
        <td>' . htmlspecialchars($row['category']) . '</td>
        <td>' . htmlspecialchars($row['index_type']) . '</td>
        <td>' . htmlspecialchars($row['collaboration']) . '</td>
        <td>' . htmlspecialchars($row['author_type']) . '</td>
        <td><a href="' . htmlspecialchars($row['file_path']) . '" target="_blank">View File</a></td>
        <td>' . htmlspecialchars($row['submission_date']) . '</td>
        <td>' . htmlspecialchars($row['validation_status']) . '</td>
        <td>' . htmlspecialchars($row['validation_datetime']) . '</td>
        <td>' . htmlspecialchars($row['paper_status']) . '</td>
         <td><a href="' . htmlspecialchars($row['publication_link']) . '" target="_blank">View Link</a></td>
    </tr>';
}

$tbl .= '</table>';

// Output the HTML content
$pdf->writeHTML($tbl, true, false, false, false, '');

// Close and output PDF document
$pdf->Output('Publication Mentorship Marvel Report.pdf', 'D');

// Close statement and connection
$stmt->close();
$conn->close();
?>
